version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: api_example_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_example_dev
    ports:
      - 5432:5432
    